// GENERATED FILE. DO NOT EDIT.
//
// Generated by `make codegen` from backend/src/Reckon/Api/Types.hs.
// To change these types, change the Haskell types and regenerate.
// CI fails if this file is out of date.

export type HealthResponse = IHealthResponse;

export interface IHealthResponse {
  databaseStatus: DatabaseStatus;
  serverVersion: string;
}

export type DatabaseStatus = "reachable" | "unreachable";
