-- | Renders the API types as a TypeScript module for the frontend.
module Reckon.Api.TypeScript
  ( renderTypeScriptModule
  ) where

import Data.Aeson.TypeScript.TH (ExportMode (..), FormattingOptions (..), defaultFormattingOptions, formatTSDeclarations')
import Data.Text (Text)
import Data.Text qualified as Text
import Reckon.Api.Types (typeScriptDeclarations)

-- | The full contents of @frontend/src/api/generated.ts@.
renderTypeScriptModule :: Text
renderTypeScriptModule =
  Text.unlines
    [ "// GENERATED FILE. DO NOT EDIT."
    , "//"
    , "// Generated by `make codegen` from backend/src/Reckon/Api/Types.hs."
    , "// To change these types, change the Haskell types and regenerate."
    , "// CI fails if this file is out of date."
    , ""
    , Text.pack (formatTSDeclarations' formattingOptions typeScriptDeclarations)
    ]
  where
    formattingOptions =
      defaultFormattingOptions
        { exportMode = ExportEach
        , numIndentSpaces = 2
        }
